Migrate to GitHub
dvsa/olcs-auth pull request #1
Opened 2023-11-30 10:02 UTC by sanakhandvsa

## Description

Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

## Before submitting (or marking as "ready for review")

- [ ] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ ] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2023-11-30 11:06 UTC, JoshuaLicense commented on composer.json
> +    },
This is for the `olcs-logging` namespaces.

2023-11-30 11:06 UTC, JoshuaLicense commented on test/src/ControllerFactory/LogoutControllerFactoryTest.php
> +namespace OlcsTest\Logging\src\ControllerFactory;
This is a `olcs-logging` namespace.

2023-12-04 11:41 UTC, JoshuaLicense requested changes
`prefer-lowest` and `prefer-stable` are installing the same Laminas MVC version (2.7.X) - be good to find out what's blocking the install to Laminas MVC `^3.0`.

2023-12-04 11:41 UTC, JoshuaLicense commented on src/ControllerFactory/ExpiredPasswordControllerFactory.php
> -     * @throws NotFoundExceptionInterfaceAlias
Does this method no longer throw these exceptions?

2023-12-04 11:41 UTC, JoshuaLicense commented on composer.json
> +        "container-interop/container-interop": "^1.2"
Could we run `--sort-packages` for Composer so that these are sorted correctly please?

2023-12-05 09:37 UTC, fibble approved these changes

2023-12-05 14:02 UTC, merged